#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GRuhaSarthaDB")]
public partial class BookingDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_BookingDetail(tbl_BookingDetail instance);
  partial void Updatetbl_BookingDetail(tbl_BookingDetail instance);
  partial void Deletetbl_BookingDetail(tbl_BookingDetail instance);
  #endregion
	
	public BookingDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GRuhaSarthaDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BookingDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookingDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookingDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookingDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_BookingDetail> tbl_BookingDetails
	{
		get
		{
			return this.GetTable<tbl_BookingDetail>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BookingDetails")]
public partial class tbl_BookingDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BookingId;
	
	private System.Nullable<int> _VendorID;
	
	private string _CustName;
	
	private string _CustEmail;
	
	private string _CustContact;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookingIdChanging(int value);
    partial void OnBookingIdChanged();
    partial void OnVendorIDChanging(System.Nullable<int> value);
    partial void OnVendorIDChanged();
    partial void OnCustNameChanging(string value);
    partial void OnCustNameChanged();
    partial void OnCustEmailChanging(string value);
    partial void OnCustEmailChanged();
    partial void OnCustContactChanging(string value);
    partial void OnCustContactChanged();
    #endregion
	
	public tbl_BookingDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BookingId
	{
		get
		{
			return this._BookingId;
		}
		set
		{
			if ((this._BookingId != value))
			{
				this.OnBookingIdChanging(value);
				this.SendPropertyChanging();
				this._BookingId = value;
				this.SendPropertyChanged("BookingId");
				this.OnBookingIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", DbType="Int")]
	public System.Nullable<int> VendorID
	{
		get
		{
			return this._VendorID;
		}
		set
		{
			if ((this._VendorID != value))
			{
				this.OnVendorIDChanging(value);
				this.SendPropertyChanging();
				this._VendorID = value;
				this.SendPropertyChanged("VendorID");
				this.OnVendorIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustName", DbType="VarChar(50)")]
	public string CustName
	{
		get
		{
			return this._CustName;
		}
		set
		{
			if ((this._CustName != value))
			{
				this.OnCustNameChanging(value);
				this.SendPropertyChanging();
				this._CustName = value;
				this.SendPropertyChanged("CustName");
				this.OnCustNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustEmail", DbType="VarChar(50)")]
	public string CustEmail
	{
		get
		{
			return this._CustEmail;
		}
		set
		{
			if ((this._CustEmail != value))
			{
				this.OnCustEmailChanging(value);
				this.SendPropertyChanging();
				this._CustEmail = value;
				this.SendPropertyChanged("CustEmail");
				this.OnCustEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustContact", DbType="NChar(12)")]
	public string CustContact
	{
		get
		{
			return this._CustContact;
		}
		set
		{
			if ((this._CustContact != value))
			{
				this.OnCustContactChanging(value);
				this.SendPropertyChanging();
				this._CustContact = value;
				this.SendPropertyChanged("CustContact");
				this.OnCustContactChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
