#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GRuhaSarthaDB")]
public partial class QuestionsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_Questionnaire(tbl_Questionnaire instance);
  partial void Updatetbl_Questionnaire(tbl_Questionnaire instance);
  partial void Deletetbl_Questionnaire(tbl_Questionnaire instance);
  #endregion
	
	public QuestionsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GRuhaSarthaDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QuestionsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuestionsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuestionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuestionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_Questionnaire> tbl_Questionnaires
	{
		get
		{
			return this.GetTable<tbl_Questionnaire>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Questionnaire")]
public partial class tbl_Questionnaire : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _QuestionId;
	
	private System.Nullable<int> _ServiceId;
	
	private string _Question;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnServiceIdChanging(System.Nullable<int> value);
    partial void OnServiceIdChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    #endregion
	
	public tbl_Questionnaire()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int QuestionId
	{
		get
		{
			return this._QuestionId;
		}
		set
		{
			if ((this._QuestionId != value))
			{
				this.OnQuestionIdChanging(value);
				this.SendPropertyChanging();
				this._QuestionId = value;
				this.SendPropertyChanged("QuestionId");
				this.OnQuestionIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceId", DbType="Int")]
	public System.Nullable<int> ServiceId
	{
		get
		{
			return this._ServiceId;
		}
		set
		{
			if ((this._ServiceId != value))
			{
				this.OnServiceIdChanging(value);
				this.SendPropertyChanging();
				this._ServiceId = value;
				this.SendPropertyChanged("ServiceId");
				this.OnServiceIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="VarChar(MAX)")]
	public string Question
	{
		get
		{
			return this._Question;
		}
		set
		{
			if ((this._Question != value))
			{
				this.OnQuestionChanging(value);
				this.SendPropertyChanging();
				this._Question = value;
				this.SendPropertyChanged("Question");
				this.OnQuestionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
