#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GRuhaSarthaDB")]
public partial class VendorDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_VendorLogin(tbl_VendorLogin instance);
  partial void Updatetbl_VendorLogin(tbl_VendorLogin instance);
  partial void Deletetbl_VendorLogin(tbl_VendorLogin instance);
  #endregion
	
	public VendorDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GRuhaSarthaDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public VendorDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VendorDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VendorDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VendorDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_VendorLogin> tbl_VendorLogins
	{
		get
		{
			return this.GetTable<tbl_VendorLogin>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_VendorLogin")]
public partial class tbl_VendorLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _VendorID;
	
	private string _VendorName;
	
	private string _VendorContact;
	
	private string _VendorEmail;
	
	private string _VendorPassword;
	
	private string _VendorProfession;
	
	private System.Nullable<int> _VisitingCharges;
	
	private System.Nullable<int> _MaxServiceDistance;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVendorIDChanging(int value);
    partial void OnVendorIDChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnVendorContactChanging(string value);
    partial void OnVendorContactChanged();
    partial void OnVendorEmailChanging(string value);
    partial void OnVendorEmailChanged();
    partial void OnVendorPasswordChanging(string value);
    partial void OnVendorPasswordChanged();
    partial void OnVendorProfessionChanging(string value);
    partial void OnVendorProfessionChanged();
    partial void OnVisitingChargesChanging(System.Nullable<int> value);
    partial void OnVisitingChargesChanged();
    partial void OnMaxServiceDistanceChanging(System.Nullable<int> value);
    partial void OnMaxServiceDistanceChanged();
    #endregion
	
	public tbl_VendorLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int VendorID
	{
		get
		{
			return this._VendorID;
		}
		set
		{
			if ((this._VendorID != value))
			{
				this.OnVendorIDChanging(value);
				this.SendPropertyChanging();
				this._VendorID = value;
				this.SendPropertyChanged("VendorID");
				this.OnVendorIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorContact", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string VendorContact
	{
		get
		{
			return this._VendorContact;
		}
		set
		{
			if ((this._VendorContact != value))
			{
				this.OnVendorContactChanging(value);
				this.SendPropertyChanging();
				this._VendorContact = value;
				this.SendPropertyChanged("VendorContact");
				this.OnVendorContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorEmail", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string VendorEmail
	{
		get
		{
			return this._VendorEmail;
		}
		set
		{
			if ((this._VendorEmail != value))
			{
				this.OnVendorEmailChanging(value);
				this.SendPropertyChanging();
				this._VendorEmail = value;
				this.SendPropertyChanged("VendorEmail");
				this.OnVendorEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorPassword", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string VendorPassword
	{
		get
		{
			return this._VendorPassword;
		}
		set
		{
			if ((this._VendorPassword != value))
			{
				this.OnVendorPasswordChanging(value);
				this.SendPropertyChanging();
				this._VendorPassword = value;
				this.SendPropertyChanged("VendorPassword");
				this.OnVendorPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorProfession", DbType="VarChar(MAX)")]
	public string VendorProfession
	{
		get
		{
			return this._VendorProfession;
		}
		set
		{
			if ((this._VendorProfession != value))
			{
				this.OnVendorProfessionChanging(value);
				this.SendPropertyChanging();
				this._VendorProfession = value;
				this.SendPropertyChanged("VendorProfession");
				this.OnVendorProfessionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitingCharges", DbType="Int")]
	public System.Nullable<int> VisitingCharges
	{
		get
		{
			return this._VisitingCharges;
		}
		set
		{
			if ((this._VisitingCharges != value))
			{
				this.OnVisitingChargesChanging(value);
				this.SendPropertyChanging();
				this._VisitingCharges = value;
				this.SendPropertyChanged("VisitingCharges");
				this.OnVisitingChargesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxServiceDistance", DbType="Int")]
	public System.Nullable<int> MaxServiceDistance
	{
		get
		{
			return this._MaxServiceDistance;
		}
		set
		{
			if ((this._MaxServiceDistance != value))
			{
				this.OnMaxServiceDistanceChanging(value);
				this.SendPropertyChanging();
				this._MaxServiceDistance = value;
				this.SendPropertyChanged("MaxServiceDistance");
				this.OnMaxServiceDistanceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
